version : "3.3"
services: 
  web:
    image: my-image-name:${IMAGE_TAG}
    ports:
         - "3000:3000"
#     volumes:
#       - my_todo_volume:/app
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: demo@123
      MYSQL_ROOT_PASSWORD: demo@123
# volumes:
#   my_todo_volume:
#     external: true


# docker volume create --name my_todo_volume --opt type=none --opt device=/home/ubuntu/90daysofdevops/Projects/volume/todo_app_volume --opt o=bind
